### ISSUE TITLE
mintupgrade error unmet dependencies

### ISSUE THREAD

**Issue by JacobsMess** [linuxmint/mintupgrade-legacy#29]
When I try to upgrade I get the following error after running mintupgrade check whilst it is simulating an upgrade.

Calculating upgrade... Error!
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libgirepository-1.0-1 : Breaks: python-gi (< 3.34.0-4~) but 3.26.1-2ubuntu1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Traceback (most recent call last):
  File "/usr/bin/mintupgrade", line 626, in <module>
    upgrader.check()
  File "/usr/bin/mintupgrade", line 398, in check
    cache.upgrade(True)
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 385, in upgrade
    self._depcache.upgrade(dist_upgrade)
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mintupgrade.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/mintupgrade", line 626, in <module>
    upgrader.check()
  File "/usr/bin/mintupgrade", line 398, in check
    cache.upgrade(True)
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 385, in upgrade
    self._depcache.upgrade(dist_upgrade)
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by Mochuleo** [comment]
During the upgrade process I was faced with a similar issue:

Holen:76 http://archive.ubuntu.com/ubuntu focal-backports/multiverse amd64 c-n-f Metadata [116 B]                                                                                  
Paketlisten werden gelesen... Fertig                                                                                                                                               
W: GPG-Fehler: http://packages.linuxmint.com ulyana Release: Die folgenden Signaturen waren ungültig: BADSIG A6616109451BBBF2 Linux Mint Repository Signing Key <root@linuxmint.com>
E: Das Depot »http://packages.linuxmint.com ulyana Release« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

  + Error detected on try #1......

  + Retrying......
Ign:1 http://packages.linuxmint.com ulyana InRelease
OK:2 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                                            
OK:3 http://security.ubuntu.com/ubuntu focal-security InRelease                                                                                                  
Holen:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [107 kB]                           
Holen:5 http://packages.linuxmint.com ulyana Release [24,1 kB]                                              
OK:6 http://archive.canonical.com/ubuntu focal InRelease                                                            
Holen:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [98,3 kB]                                        
Holen:8 http://packages.linuxmint.com ulyana Release.gpg [819 B]                     
Ign:8 http://packages.linuxmint.com ulyana Release.gpg                                          
Paketlisten werden gelesen... Fertig
W: GPG-Fehler: http://packages.linuxmint.com ulyana Release: Die folgenden Signaturen waren ungültig: BADSIG A6616109451BBBF2 Linux Mint Repository Signing Key <root@linuxmint.com>
E: Das Depot »http://packages.linuxmint.com ulyana Release« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).

  + Error detected on try #2......

  + Downloading upgrade packages...

Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fehler!
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 libgirepository-1.0-1 : Beschädigt: python-gi (< 3.34.0-4~) aber 3.26.1-2ubuntu1 soll installiert werden
E: Fehler: Unterbrechungen durch pkgProblemResolver::Resolve hervorgerufen; dies könnte durch zurückgehaltene Pakete verursacht worden sein.

------------------------------------------------
!!  ERROR: Failed to download packages for the upgrade.
!!  Exiting.
------------------------------------------------

  + Restoring your backed up APT sources...

mochuleo@mochuleo-Laptop:~$

**Comment by kemkerj3** [comment]
Solution?

I'm getting the same error, except mine is not restoring my backed up APT resources.  I had to restore them through Software-Sources.  As per your post on https://blog.linuxmint.com/?p=3946, here is some output from diagnostics:

~$ inxi -r
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http://packages.linuxmint.com tricia main upstream import backport
           2: deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http://archive.canonical.com/ubuntu/ bionic partner
~$ apt policy
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://archive.canonical.com/ubuntu bionic/partner i386 Packages
     release v=18.04,o=Canonical,a=bionic,n=bionic,l=Partner archive,c=partner,b=i386
     origin archive.canonical.com
 500 http://archive.canonical.com/ubuntu bionic/partner amd64 Packages
     release v=18.04,o=Canonical,a=bionic,n=bionic,l=Partner archive,c=partner,b=amd64
     origin archive.canonical.com
 500 http://security.ubuntu.com/ubuntu bionic-security/multiverse i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=multiverse,b=i386
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=multiverse,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=universe,b=i386
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=universe,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/restricted i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=restricted,b=i386
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=restricted,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=main,b=i386
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=main,b=amd64
     origin security.ubuntu.com
 100 http://archive.ubuntu.com/ubuntu bionic-backports/universe i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-backports,n=bionic,l=Ubuntu,c=universe,b=i386
     origin archive.ubuntu.com
 100 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-backports,n=bionic,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
 100 http://archive.ubuntu.com/ubuntu bionic-backports/main i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-backports,n=bionic,l=Ubuntu,c=main,b=i386
     origin archive.ubuntu.com
 100 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-backports,n=bionic,l=Ubuntu,c=main,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=multiverse,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=multiverse,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=universe,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/restricted i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=restricted,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=restricted,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=main,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=main,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/multiverse i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=multiverse,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=multiverse,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/universe i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=universe,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/restricted i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=restricted,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=restricted,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/main i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=main,b=i386
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=main,b=amd64
     origin archive.ubuntu.com
 500 http://packages.linuxmint.com tricia/backport i386 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=backport,b=i386
     origin packages.linuxmint.com
 500 http://packages.linuxmint.com tricia/backport amd64 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=backport,b=amd64
     origin packages.linuxmint.com
 500 http://packages.linuxmint.com tricia/import i386 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=import,b=i386
     origin packages.linuxmint.com
 500 http://packages.linuxmint.com tricia/import amd64 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=import,b=amd64
     origin packages.linuxmint.com
 700 http://packages.linuxmint.com tricia/upstream i386 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=upstream,b=i386
     origin packages.linuxmint.com
 700 http://packages.linuxmint.com tricia/upstream amd64 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=upstream,b=amd64
     origin packages.linuxmint.com
 500 http://packages.linuxmint.com tricia/main i386 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=main,b=i386
     origin packages.linuxmint.com
 500 http://packages.linuxmint.com tricia/main amd64 Packages
     release v=19.3,o=linuxmint,a=tricia,n=tricia,l=linuxmint,c=main,b=amd64
     origin packages.linuxmint.com
Pinned packages:

**Comment by alvarro616** [comment]
> When I try to upgrade I get the following error after running mintupgrade check whilst it is simulating an upgrade.
> 
> Calculating upgrade... Error!
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies.
> libgirepository-1.0-1 : Breaks: python-gi (< 3.34.0-4~) but 3.26.1-2ubuntu1 is to be installed
> E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> Traceback (most recent call last):
> File "/usr/bin/mintupgrade", line 626, in
> upgrader.check()
> File "/usr/bin/mintupgrade", line 398, in check
> cache.upgrade(True)
> File "/usr/lib/python3/dist-packages/apt/cache.py", line 385, in upgrade
> self._depcache.upgrade(dist_upgrade)
> apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> Error in sys.excepthook:
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
> os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mintupgrade.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
> File "/usr/bin/mintupgrade", line 626, in
> upgrader.check()
> File "/usr/bin/mintupgrade", line 398, in check
> cache.upgrade(True)
> File "/usr/lib/python3/dist-packages/apt/cache.py", line 385, in upgrade
> self._depcache.upgrade(dist_upgrade)
> apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

to solve these problem , i remove python-gi from synaptic package manager.. well the upgrade is running

**Comment by FabriceFABS** [comment]
> to solve these problem , i remove python-gi from synaptic package manager.. well the upgrade is running

Many thanks 👍 it worked for me.
I had also to do the same to another package.

**Comment by Techguyprivate** [comment]
Any solutions? Exact same problem.

Trying to remove the  the python-gi shows that mintmenu and bluberry depend on it. 

So what to do?

I am stuck and not upgrading.
