### ISSUE TITLE
upgrade check error

### ISSUE THREAD

**Issue by Maintech3** [linuxmint/mintupgrade-legacy#33]
Reading state information... Done
Calculating upgrade... Error!
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgirepository-1.0-1 : Breaks: python-gi (< 3.34.0-4~) but 3.26.1-2ubuntu1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Traceback (most recent call last):
  File "/usr/bin/mintupgrade", line 627, in <module>
    upgrader.check()
  File "/usr/bin/mintupgrade", line 399, in check
    cache.upgrade(True)
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 385, in upgrade
    self._depcache.upgrade(dist_upgrade)
apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

I tried to downgrade and remove all foreign packages. Skype and Microsoft fonts were the only ones listed for removal. As long as I continue to get this error I don't feel like I should try to continue with the upgrade. Any assistance would be appreciated.

**Comment by razerrazer** [comment]
We have the same problem, can you please share your PPAs?

**Comment by mtwebster** [comment]
That 3.26.1 version is wrong, the new repos should be attempting to install python-gi 3.36.0-1, and libgirepository-1.64.1-1.

3.26.1-2 is the bionic/Mint 19 version.  This should be getting upgraded.  Can you check `apt-cache rdepends python-gi` and see if anything catches your eye? (this will show packages that depend on python-gi).

**Comment by razerrazer** [comment]
python-gi
Reverse Depends:
  python-gi-dbg
  python-aptdaemon.gtk3widgets
  python-aptdaemon
  virtinst
  virt-manager
  python-gst-1.0-dbg
  python-gst-1.0
  python-gobject
  python-gi-cairo
  python-aptdaemon.gtk3widgets
  python-aptdaemon
  avahi-discover
  python-gi-dev
  python-pyatspi
  gir1.2-gtk-3.0
  thawab
  othman
  vizigrep
  virtinst
  virt-manager
  unity-scope-sshsearch
  unity-scope-launchpad
  ubuntustudio-controls
  ubuntu-kylin-software-center
  tuned-gtk
  tuned
  tortoisehg-nautilus
  tortoisehg-caja
  tortoisehg
  terminator
  sugar-write-activity
  sugar-read-activity
  sugar-memorize-activity
  sugar-log-activity
  sugar-calculate-activity
  sugar-browse-activity
  solaar
  smartshine
  sat-xmpp-primitivus
  sat-xmpp-jp
  radiotray
  qreator
  python-zeitgeist
  python-v-sim
  python-sugar3
  python-send2trash
  python-rgain
  python-pydbus
  python-gi-dbg
  python-nautilus
  python-laditools
  python-gwebsockets
  python-gtkspellcheck
  python-gst-1.0-dbg
  python-gst-1.0
  python-gobject
  python-gi-cairo
  python-fonttools
  python-dogtail
  python-dbusmock
  python-dbus-tests
  python-carquinyol
  python-autopilot
  python-aptdaemon.gtk3widgets
  python-aptdaemon
  pyhoca-gui
  pychess
  pulseaudio-dlna
  ocrfeeder
  mozo
  mate-applets
  mat
  mandos
  laditools
  isenkram-cli
  isenkram
  indicator-china-weather
  ibus-pinyin
  ibus-braille
  ibus-array
  gvb
  gnome-mousetrap
  gnome-keysign
  gnat-gps
  gedit-developer-plugins
  ganyremote
  flowblade
  exfalso
  dnssec-trigger
  caja-rename
  caja-owncloud
  caja-admin
  bookletimposer
  avahi-discover
  autokey-gtk
  alacarte
  python-secretstorage
 |python-pyperclip
  python-keyrings.alt
  python-gi-dev
  gir1.2-gtk-3.0
  python-dbus
  blueberry
  glade2script
  mintupload

**Comment by shivkumarjha1** [comment]
I am stuck on this. It won't even do regular updates. How do I go back where I was before...

**Comment by mtwebster** [comment]
That was early enough in the process you should be able to run `mintupgrade restore-sources` to go back to 19.3.  Did you make a timeshift backup? You probably should (after you restore).

edit: restore-sources, not restore.

**Comment by shivkumarjha1** [comment]
I did. I will use timeshift. Ty.

**Comment by razerrazer** [comment]
I tried to remove every PPAs but the problem ramains.. the python install will not working.

dpkg: error processing package python3-gi (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 python3
 python3-gi
E: Sub-process /usr/bin/dpkg returned an error code (1)

  + An issue was detected during the upgrade, running dist-upgrade in manual mode....
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 aptitude : Depends: libapt-pkg5.0 (>= 1.1) but it is not installable
 libapt-inst2.0 : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libapt-pkg-perl : Depends: perlapi-5.26.1 but it is not installable
                      Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libcairo-perl : Depends: perlapi-5.26.1 but it is not installable
 libcommon-sense-perl : Depends: perlapi-5.26.1 but it is not installable
                        Depends: perl (< 5.26.2~) but 5.30.0-9build1 is installed
 libept1.5.0 : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
 libfcgi-perl : Depends: perlapi-5.26.0 but it is not installable
 libfile-fcntllock-perl : Depends: perlapi-5.26.0 but it is not installable
 libglib-perl : Depends: perlapi-5.26.0 but it is not installable
 libgtk2-perl : Depends: perlapi-5.26.0 but it is not installable
 libharfbuzz-dev : Depends: gir1.2-harfbuzz-0.0 (= 2.6.4-1ubuntu4) but 1.7.2-1ubuntu1 is installed
 libhtml-parser-perl : Depends: perlapi-5.26.0 but it is not installable
 libimage-magick-q16-perl : Depends: perlapi-5.26.1 but it is not installable
 libio-pty-perl : Depends: perlapi-5.26.0 but it is not installable
 liblist-moreutils-perl : Depends: perlapi-5.26.0 but it is not installable
 liblocale-gettext-perl : PreDepends: perlapi-5.26.0 but it is not installable
 libnet-dbus-perl : Depends: perlapi-5.26.0 but it is not installable
 libnet-libidn-perl : Depends: perlapi-5.26.0 but it is not installable
 libpango-perl : Depends: perlapi-5.26.0 but it is not installable
 libperlio-gzip-perl : Depends: perlapi-5.26.0 but it is not installable
 libsocket6-perl : Depends: perlapi-5.26.0 but it is not installable
 libsub-name-perl : Depends: perlapi-5.26.0 but it is not installable
 libtext-charwidth-perl : Depends: perlapi-5.26.0 but it is not installable
 libtext-iconv-perl : Depends: perlapi-5.26.0 but it is not installable
 libuuid-perl : Depends: perlapi-5.26.0 but it is not installable
 libxml-parser-perl : Depends: perlapi-5.26.0 but it is not installable
 onboard : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-apt : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
               Depends: libapt-pkg5.0 (>= 1.6.5~) but it is not installable
 python3-brlapi : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-cairo : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-crypto : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-cups : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-dbus : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 python3-gi-cairo : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
                    Depends: python3-gi (= 3.26.1-2ubuntu1) but 3.36.0-1 is installed
 python3-pycurl : Depends: python3 (< 3.7) but 3.8.2-0ubuntu2 is installed
 synaptic : Depends: libapt-pkg5.0 (>= 1.1~exp9) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

------------------------------------------------
!!  ERROR: Failed to dist-upgrade some of the packages. Please review the error message, use APT to fix the situation and try again.
!!  Exiting.
------------------------------------------------

**Comment by razerrazer** [comment]
This issue have been solved, i removed everything under PPAs + Removed everything under Additional repository's :

Removed all foreign packages and downgraded foreign packages.

**Comment by Techguyprivate** [comment]
> This issue have been solved, i removed everything under PPAs + Removed everything under Additional repository's :
> 
> Removed all foreign packages and downgraded foreign packages.

How to restore the PPAs? After upgrade, all my PPAs and additional repos are gone. 

I am not getting any updates due to the repos being gone. I am getting only linux mint updates, no updates of other softwares like brave browser or etc which I have installed.


    I have disabled or unchecked all the PPAs and additional repositories in software sources before upgrading from 19.3 to 20 as mentioned in how to upgrade instruction.

    I haven't removed or deleted any PPAs or additional 3rd party repos before upgrade.

    I have many PPAs and 3rd party repos.

So main issue or problem is

How to restore PPAs and additional 3rd party reps after upgrade?

![Screenshot from 2020-07-22 19-07-17](https://user-images.githubusercontent.com/43615747/88183863-87a5d280-cc21-11ea-890d-2fc81162f1d4.png)
![Screenshot from 2020-07-22 19-07-13](https://user-images.githubusercontent.com/43615747/88183867-896f9600-cc21-11ea-9303-c9c87ac9c1b4.png)

**Comment by tiberiustribun** [comment]
I have the same problem. All PPAs and foreign packages were removed, still I get this error

    The following packages have unmet dependencies:
     libgirepository-1.0-1 : Breaks: python-gi (< 3.34.0-4~) but 3.26.1-2ubuntu1 is to be installed
    E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
    Traceback (most recent call last):
      File "/usr/bin/mintupgrade", line 726, in <module>
        upgrader.check()
      File "/usr/bin/mintupgrade", line 498, in check
        cache.upgrade(True)
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 385, in upgrade
        self._depcache.upgrade(dist_upgrade)
    apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
        s.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_mintupgrade.1000.crash'
    
    Original exception was:
    Traceback (most recent call last):
      File "/usr/bin/mintupgrade", line 726, in <module>
       upgrader.check()
      File "/usr/bin/mintupgrade", line 498, in check
        cache.upgrade(True)
      File "/usr/lib/python3/dist-packages/apt/cache.py", line 385, in upgrade
        self._depcache.upgrade(dist_upgrade)
    apt_pkg.Error: E:Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

The only thing I could remember that might be the issue is that I at some point manually upgraded the amdgpu driver package from a AMD download package. Hence 'mintupgrade check' originally reported the following:

    - amdgpu
    - amdgpu-core
    - amdgpu-dkms
    - amdgpu-dkms-firmware
    - amdgpu-lib
    - amdgpu-lib32
    - amdgpu-pro-pin
    - glamor-amdgpu
    - gst-omx-amdgpu
    - libdrm-amdgpu-amdgpu1
    - libdrm-amdgpu-amdgpu1:i386
    - libdrm-amdgpu-common
    - libdrm-amdgpu-radeon1
    - libdrm-amdgpu-radeon1:i386
    - libdrm2-amdgpu
    - libdrm2-amdgpu:i386
    - libegl1-amdgpu-mesa
    - libegl1-amdgpu-mesa-drivers
    - libegl1-amdgpu-mesa-drivers:i386
    - libegl1-amdgpu-mesa:i386
    - libgbm1-amdgpu
    - libgbm1-amdgpu:i386
    - libgl1-amdgpu-mesa-dri
    - libgl1-amdgpu-mesa-dri:i386
    - libgl1-amdgpu-mesa-glx
    - libgl1-amdgpu-mesa-glx:i386
    - libglapi-amdgpu-mesa
    - libglapi-amdgpu-mesa:i386
    - libgles1-amdgpu-mesa
    - libgles1-amdgpu-mesa:i386
    - libgles2-amdgpu-mesa
    - libgles2-amdgpu-mesa:i386
    - libllvm9.0-amdgpu
    - libllvm9.0-amdgpu:i386
    - libosmesa6-amdgpu
    - libosmesa6-amdgpu:i386
    - libxatracker2-amdgpu
    - libxatracker2-amdgpu:i386
    - mesa-amdgpu-omx-drivers
    - mesa-amdgpu-va-drivers
    - mesa-amdgpu-va-drivers:i386
    - mesa-amdgpu-vdpau-drivers
    - mesa-amdgpu-vdpau-drivers:i386
    - xserver-xorg-amdgpu-video-amdgpu

    The packages above are not from the official repositories. If you experience issues, or for a safe upgrade, do not continue, remove them with 'Software Sources -> Maintenance -> Remove Foreign Packages' and re-run the upgrade.

I have since removed those packages so 'Software Sources -> Maintenance -> Remove Foreign Packages' reports no foreign packages present. But in the process I remembered that during installation of one of the official AMD driver packages (which come as binary installation packages) I've had problems with libgirepository and python-gi/python3-gi. I can't remember though what I did back then.

Any pointers to what I can do to resolve the situation would be greatly appreciated. 

Besides the upgrade not working, 'mintupgrade check' in this case adds to the confusion by not failing gracefully and restoring the original package sources. I have to run 'mintupgrade restore-sources' afterwards to get updates back to working condition.

**Comment by AnomalRoil** [comment]
Solved on my side by doing a :
`sudo apt remove python-gi` before running the `mintupgrade`
and re-installing it after upgrading.

**Comment by dell-devil** [comment]
Getting this error while installing Zenmap 

--------------------------------------------------------------------

The following packages have unmet dependencies:
 gir1.2-gtk-3.0 : Breaks: python-gi (< 3.18) but 3.2.2-2 is to be installed
 libgirepository-1.0-1 : Breaks: python-gi (< 3.34.0-4~) but 3.2.2-2 is to be installed
 libpython2.7-minimal : Breaks: python-minimal (< 2.7.18) but 2.7.3-4+deb7u1 is to be installed
 python-is-python2 : Breaks: python-minimal but 2.7.3-4+deb7u1 is to be installed
 python2-minimal : Breaks: python-minimal (< 2.7.15-2) but 2.7.3-4+deb7u1 is to be installed
 python2.7 : Breaks: python-minimal (< 2.7.18) but 2.7.3-4+deb7u1 is to be installed
 python2.7-minimal : Breaks: python-minimal (< 2.7.18) but 2.7.3-4+deb7u1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

------------------------------------------------------------------------------------------------------------
